// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectAssistant.EntityModel;

#nullable disable

namespace ProjectAssistant.EntityModel.Migrations
{
    [DbContext(typeof(BackendDBContext))]
    [Migration("20251014100804_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Chinese_Taiwan_Stroke_CI_AS")
                .HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("ProjectAssistant.EntityModel.Models.MyUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Salt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("MyUser");
                });

            modelBuilder.Entity("ProjectAssistant.EntityModel.Models.MyUserRoleView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MyUserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleViewId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MyUserId");

                    b.HasIndex("RoleViewId");

                    b.ToTable("MyUserRoleView");
                });

            modelBuilder.Entity("ProjectAssistant.EntityModel.Models.RoleView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RoleView");
                });

            modelBuilder.Entity("ProjectAssistant.EntityModel.Models.MyUserRoleView", b =>
                {
                    b.HasOne("ProjectAssistant.EntityModel.Models.MyUser", "MyUser")
                        .WithMany("MyUserRoleView")
                        .HasForeignKey("MyUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProjectAssistant.EntityModel.Models.RoleView", "RoleView")
                        .WithMany("MyUserRoleView")
                        .HasForeignKey("RoleViewId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MyUser");

                    b.Navigation("RoleView");
                });

            modelBuilder.Entity("ProjectAssistant.EntityModel.Models.MyUser", b =>
                {
                    b.Navigation("MyUserRoleView");
                });

            modelBuilder.Entity("ProjectAssistant.EntityModel.Models.RoleView", b =>
                {
                    b.Navigation("MyUserRoleView");
                });
#pragma warning restore 612, 618
        }
    }
}
